/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsImportRouteImport } from './routes/projects/import'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSecretsRouteImport } from './routes/projects/$projectId/secrets'
import { Route as ProjectsProjectIdRunsRouteImport } from './routes/projects/$projectId/runs'
import { Route as ProjectsProjectIdHostsRouteImport } from './routes/projects/$projectId/hosts'
import { Route as ProjectsProjectIdDashboardRouteImport } from './routes/projects/$projectId/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectsProjectIdHostsIndexRouteImport } from './routes/projects/$projectId/hosts/index'
import { Route as ProjectsProjectIdSetupSettingsRouteImport } from './routes/projects/$projectId/setup/settings'
import { Route as ProjectsProjectIdSetupFleetRouteImport } from './routes/projects/$projectId/setup/fleet'
import { Route as ProjectsProjectIdSetupDoctorRouteImport } from './routes/projects/$projectId/setup/doctor'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects/$projectId/runs/$runId'
import { Route as ProjectsProjectIdHostsSettingsRouteImport } from './routes/projects/$projectId/hosts/settings'
import { Route as ProjectsProjectIdHostsSecretsRouteImport } from './routes/projects/$projectId/hosts/secrets'
import { Route as ProjectsProjectIdHostsRestartRouteImport } from './routes/projects/$projectId/hosts/restart'
import { Route as ProjectsProjectIdHostsOverviewRouteImport } from './routes/projects/$projectId/hosts/overview'
import { Route as ProjectsProjectIdHostsLogsRouteImport } from './routes/projects/$projectId/hosts/logs'
import { Route as ProjectsProjectIdHostsDeployRouteImport } from './routes/projects/$projectId/hosts/deploy'
import { Route as ProjectsProjectIdHostsBootstrapRouteImport } from './routes/projects/$projectId/hosts/bootstrap'
import { Route as ProjectsProjectIdHostsAuditRouteImport } from './routes/projects/$projectId/hosts/audit'
import { Route as ProjectsProjectIdHostsAgentsRouteImport } from './routes/projects/$projectId/hosts/agents'
import { Route as ProjectsProjectIdAdvancedEditorRouteImport } from './routes/projects/$projectId/advanced/editor'
import { Route as ProjectsProjectIdAdvancedCommandsRouteImport } from './routes/projects/$projectId/advanced/commands'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsImportRoute = ProjectsImportRouteImport.update({
  id: '/projects/import',
  path: '/projects/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSecretsRoute =
  ProjectsProjectIdSecretsRouteImport.update({
    id: '/projects/$projectId/secrets',
    path: '/projects/$projectId/secrets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRunsRoute = ProjectsProjectIdRunsRouteImport.update({
  id: '/projects/$projectId/runs',
  path: '/projects/$projectId/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdHostsRoute = ProjectsProjectIdHostsRouteImport.update({
  id: '/projects/$projectId/hosts',
  path: '/projects/$projectId/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdDashboardRoute =
  ProjectsProjectIdDashboardRouteImport.update({
    id: '/projects/$projectId/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdHostsIndexRoute =
  ProjectsProjectIdHostsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdSetupSettingsRoute =
  ProjectsProjectIdSetupSettingsRouteImport.update({
    id: '/projects/$projectId/setup/settings',
    path: '/projects/$projectId/setup/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdSetupFleetRoute =
  ProjectsProjectIdSetupFleetRouteImport.update({
    id: '/projects/$projectId/setup/fleet',
    path: '/projects/$projectId/setup/fleet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdSetupDoctorRoute =
  ProjectsProjectIdSetupDoctorRouteImport.update({
    id: '/projects/$projectId/setup/doctor',
    path: '/projects/$projectId/setup/doctor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ProjectsProjectIdRunsRoute,
  } as any)
const ProjectsProjectIdHostsSettingsRoute =
  ProjectsProjectIdHostsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsSecretsRoute =
  ProjectsProjectIdHostsSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsRestartRoute =
  ProjectsProjectIdHostsRestartRouteImport.update({
    id: '/restart',
    path: '/restart',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsOverviewRoute =
  ProjectsProjectIdHostsOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsLogsRoute =
  ProjectsProjectIdHostsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsDeployRoute =
  ProjectsProjectIdHostsDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsBootstrapRoute =
  ProjectsProjectIdHostsBootstrapRouteImport.update({
    id: '/bootstrap',
    path: '/bootstrap',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsAuditRoute =
  ProjectsProjectIdHostsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdHostsAgentsRoute =
  ProjectsProjectIdHostsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => ProjectsProjectIdHostsRoute,
  } as any)
const ProjectsProjectIdAdvancedEditorRoute =
  ProjectsProjectIdAdvancedEditorRouteImport.update({
    id: '/projects/$projectId/advanced/editor',
    path: '/projects/$projectId/advanced/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdAdvancedCommandsRoute =
  ProjectsProjectIdAdvancedCommandsRouteImport.update({
    id: '/projects/$projectId/advanced/commands',
    path: '/projects/$projectId/advanced/commands',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRoute
  '/projects/$projectId/hosts': typeof ProjectsProjectIdHostsRouteWithChildren
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRouteWithChildren
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/advanced/commands': typeof ProjectsProjectIdAdvancedCommandsRoute
  '/projects/$projectId/advanced/editor': typeof ProjectsProjectIdAdvancedEditorRoute
  '/projects/$projectId/hosts/agents': typeof ProjectsProjectIdHostsAgentsRoute
  '/projects/$projectId/hosts/audit': typeof ProjectsProjectIdHostsAuditRoute
  '/projects/$projectId/hosts/bootstrap': typeof ProjectsProjectIdHostsBootstrapRoute
  '/projects/$projectId/hosts/deploy': typeof ProjectsProjectIdHostsDeployRoute
  '/projects/$projectId/hosts/logs': typeof ProjectsProjectIdHostsLogsRoute
  '/projects/$projectId/hosts/overview': typeof ProjectsProjectIdHostsOverviewRoute
  '/projects/$projectId/hosts/restart': typeof ProjectsProjectIdHostsRestartRoute
  '/projects/$projectId/hosts/secrets': typeof ProjectsProjectIdHostsSecretsRoute
  '/projects/$projectId/hosts/settings': typeof ProjectsProjectIdHostsSettingsRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/setup/doctor': typeof ProjectsProjectIdSetupDoctorRoute
  '/projects/$projectId/setup/fleet': typeof ProjectsProjectIdSetupFleetRoute
  '/projects/$projectId/setup/settings': typeof ProjectsProjectIdSetupSettingsRoute
  '/projects/$projectId/hosts/': typeof ProjectsProjectIdHostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRoute
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRouteWithChildren
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/advanced/commands': typeof ProjectsProjectIdAdvancedCommandsRoute
  '/projects/$projectId/advanced/editor': typeof ProjectsProjectIdAdvancedEditorRoute
  '/projects/$projectId/hosts/agents': typeof ProjectsProjectIdHostsAgentsRoute
  '/projects/$projectId/hosts/audit': typeof ProjectsProjectIdHostsAuditRoute
  '/projects/$projectId/hosts/bootstrap': typeof ProjectsProjectIdHostsBootstrapRoute
  '/projects/$projectId/hosts/deploy': typeof ProjectsProjectIdHostsDeployRoute
  '/projects/$projectId/hosts/logs': typeof ProjectsProjectIdHostsLogsRoute
  '/projects/$projectId/hosts/overview': typeof ProjectsProjectIdHostsOverviewRoute
  '/projects/$projectId/hosts/restart': typeof ProjectsProjectIdHostsRestartRoute
  '/projects/$projectId/hosts/secrets': typeof ProjectsProjectIdHostsSecretsRoute
  '/projects/$projectId/hosts/settings': typeof ProjectsProjectIdHostsSettingsRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/setup/doctor': typeof ProjectsProjectIdSetupDoctorRoute
  '/projects/$projectId/setup/fleet': typeof ProjectsProjectIdSetupFleetRoute
  '/projects/$projectId/setup/settings': typeof ProjectsProjectIdSetupSettingsRoute
  '/projects/$projectId/hosts': typeof ProjectsProjectIdHostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$projectId/dashboard': typeof ProjectsProjectIdDashboardRoute
  '/projects/$projectId/hosts': typeof ProjectsProjectIdHostsRouteWithChildren
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRouteWithChildren
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/advanced/commands': typeof ProjectsProjectIdAdvancedCommandsRoute
  '/projects/$projectId/advanced/editor': typeof ProjectsProjectIdAdvancedEditorRoute
  '/projects/$projectId/hosts/agents': typeof ProjectsProjectIdHostsAgentsRoute
  '/projects/$projectId/hosts/audit': typeof ProjectsProjectIdHostsAuditRoute
  '/projects/$projectId/hosts/bootstrap': typeof ProjectsProjectIdHostsBootstrapRoute
  '/projects/$projectId/hosts/deploy': typeof ProjectsProjectIdHostsDeployRoute
  '/projects/$projectId/hosts/logs': typeof ProjectsProjectIdHostsLogsRoute
  '/projects/$projectId/hosts/overview': typeof ProjectsProjectIdHostsOverviewRoute
  '/projects/$projectId/hosts/restart': typeof ProjectsProjectIdHostsRestartRoute
  '/projects/$projectId/hosts/secrets': typeof ProjectsProjectIdHostsSecretsRoute
  '/projects/$projectId/hosts/settings': typeof ProjectsProjectIdHostsSettingsRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/projects/$projectId/setup/doctor': typeof ProjectsProjectIdSetupDoctorRoute
  '/projects/$projectId/setup/fleet': typeof ProjectsProjectIdSetupFleetRoute
  '/projects/$projectId/setup/settings': typeof ProjectsProjectIdSetupSettingsRoute
  '/projects/$projectId/hosts/': typeof ProjectsProjectIdHostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/projects/import'
    | '/projects/new'
    | '/projects/'
    | '/api/auth/$'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/hosts'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId/'
    | '/projects/$projectId/advanced/commands'
    | '/projects/$projectId/advanced/editor'
    | '/projects/$projectId/hosts/agents'
    | '/projects/$projectId/hosts/audit'
    | '/projects/$projectId/hosts/bootstrap'
    | '/projects/$projectId/hosts/deploy'
    | '/projects/$projectId/hosts/logs'
    | '/projects/$projectId/hosts/overview'
    | '/projects/$projectId/hosts/restart'
    | '/projects/$projectId/hosts/secrets'
    | '/projects/$projectId/hosts/settings'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/setup/doctor'
    | '/projects/$projectId/setup/fleet'
    | '/projects/$projectId/setup/settings'
    | '/projects/$projectId/hosts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/projects/import'
    | '/projects/new'
    | '/projects'
    | '/api/auth/$'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId'
    | '/projects/$projectId/advanced/commands'
    | '/projects/$projectId/advanced/editor'
    | '/projects/$projectId/hosts/agents'
    | '/projects/$projectId/hosts/audit'
    | '/projects/$projectId/hosts/bootstrap'
    | '/projects/$projectId/hosts/deploy'
    | '/projects/$projectId/hosts/logs'
    | '/projects/$projectId/hosts/overview'
    | '/projects/$projectId/hosts/restart'
    | '/projects/$projectId/hosts/secrets'
    | '/projects/$projectId/hosts/settings'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/setup/doctor'
    | '/projects/$projectId/setup/fleet'
    | '/projects/$projectId/setup/settings'
    | '/projects/$projectId/hosts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/projects/import'
    | '/projects/new'
    | '/projects/'
    | '/api/auth/$'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/hosts'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId/'
    | '/projects/$projectId/advanced/commands'
    | '/projects/$projectId/advanced/editor'
    | '/projects/$projectId/hosts/agents'
    | '/projects/$projectId/hosts/audit'
    | '/projects/$projectId/hosts/bootstrap'
    | '/projects/$projectId/hosts/deploy'
    | '/projects/$projectId/hosts/logs'
    | '/projects/$projectId/hosts/overview'
    | '/projects/$projectId/hosts/restart'
    | '/projects/$projectId/hosts/secrets'
    | '/projects/$projectId/hosts/settings'
    | '/projects/$projectId/runs/$runId'
    | '/projects/$projectId/setup/doctor'
    | '/projects/$projectId/setup/fleet'
    | '/projects/$projectId/setup/settings'
    | '/projects/$projectId/hosts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  ProjectsImportRoute: typeof ProjectsImportRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProjectsProjectIdDashboardRoute: typeof ProjectsProjectIdDashboardRoute
  ProjectsProjectIdHostsRoute: typeof ProjectsProjectIdHostsRouteWithChildren
  ProjectsProjectIdRunsRoute: typeof ProjectsProjectIdRunsRouteWithChildren
  ProjectsProjectIdSecretsRoute: typeof ProjectsProjectIdSecretsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdAdvancedCommandsRoute: typeof ProjectsProjectIdAdvancedCommandsRoute
  ProjectsProjectIdAdvancedEditorRoute: typeof ProjectsProjectIdAdvancedEditorRoute
  ProjectsProjectIdSetupDoctorRoute: typeof ProjectsProjectIdSetupDoctorRoute
  ProjectsProjectIdSetupFleetRoute: typeof ProjectsProjectIdSetupFleetRoute
  ProjectsProjectIdSetupSettingsRoute: typeof ProjectsProjectIdSetupSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/import': {
      id: '/projects/import'
      path: '/projects/import'
      fullPath: '/projects/import'
      preLoaderRoute: typeof ProjectsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/secrets': {
      id: '/projects/$projectId/secrets'
      path: '/projects/$projectId/secrets'
      fullPath: '/projects/$projectId/secrets'
      preLoaderRoute: typeof ProjectsProjectIdSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/runs': {
      id: '/projects/$projectId/runs'
      path: '/projects/$projectId/runs'
      fullPath: '/projects/$projectId/runs'
      preLoaderRoute: typeof ProjectsProjectIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/hosts': {
      id: '/projects/$projectId/hosts'
      path: '/projects/$projectId/hosts'
      fullPath: '/projects/$projectId/hosts'
      preLoaderRoute: typeof ProjectsProjectIdHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/dashboard': {
      id: '/projects/$projectId/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof ProjectsProjectIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/hosts/': {
      id: '/projects/$projectId/hosts/'
      path: '/'
      fullPath: '/projects/$projectId/hosts/'
      preLoaderRoute: typeof ProjectsProjectIdHostsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/setup/settings': {
      id: '/projects/$projectId/setup/settings'
      path: '/projects/$projectId/setup/settings'
      fullPath: '/projects/$projectId/setup/settings'
      preLoaderRoute: typeof ProjectsProjectIdSetupSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/setup/fleet': {
      id: '/projects/$projectId/setup/fleet'
      path: '/projects/$projectId/setup/fleet'
      fullPath: '/projects/$projectId/setup/fleet'
      preLoaderRoute: typeof ProjectsProjectIdSetupFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/setup/doctor': {
      id: '/projects/$projectId/setup/doctor'
      path: '/projects/$projectId/setup/doctor'
      fullPath: '/projects/$projectId/setup/doctor'
      preLoaderRoute: typeof ProjectsProjectIdSetupDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/runs/$runId': {
      id: '/projects/$projectId/runs/$runId'
      path: '/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdRunsRoute
    }
    '/projects/$projectId/hosts/settings': {
      id: '/projects/$projectId/hosts/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/hosts/settings'
      preLoaderRoute: typeof ProjectsProjectIdHostsSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/secrets': {
      id: '/projects/$projectId/hosts/secrets'
      path: '/secrets'
      fullPath: '/projects/$projectId/hosts/secrets'
      preLoaderRoute: typeof ProjectsProjectIdHostsSecretsRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/restart': {
      id: '/projects/$projectId/hosts/restart'
      path: '/restart'
      fullPath: '/projects/$projectId/hosts/restart'
      preLoaderRoute: typeof ProjectsProjectIdHostsRestartRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/overview': {
      id: '/projects/$projectId/hosts/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/hosts/overview'
      preLoaderRoute: typeof ProjectsProjectIdHostsOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/logs': {
      id: '/projects/$projectId/hosts/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/hosts/logs'
      preLoaderRoute: typeof ProjectsProjectIdHostsLogsRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/deploy': {
      id: '/projects/$projectId/hosts/deploy'
      path: '/deploy'
      fullPath: '/projects/$projectId/hosts/deploy'
      preLoaderRoute: typeof ProjectsProjectIdHostsDeployRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/bootstrap': {
      id: '/projects/$projectId/hosts/bootstrap'
      path: '/bootstrap'
      fullPath: '/projects/$projectId/hosts/bootstrap'
      preLoaderRoute: typeof ProjectsProjectIdHostsBootstrapRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/audit': {
      id: '/projects/$projectId/hosts/audit'
      path: '/audit'
      fullPath: '/projects/$projectId/hosts/audit'
      preLoaderRoute: typeof ProjectsProjectIdHostsAuditRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/hosts/agents': {
      id: '/projects/$projectId/hosts/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/hosts/agents'
      preLoaderRoute: typeof ProjectsProjectIdHostsAgentsRouteImport
      parentRoute: typeof ProjectsProjectIdHostsRoute
    }
    '/projects/$projectId/advanced/editor': {
      id: '/projects/$projectId/advanced/editor'
      path: '/projects/$projectId/advanced/editor'
      fullPath: '/projects/$projectId/advanced/editor'
      preLoaderRoute: typeof ProjectsProjectIdAdvancedEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/advanced/commands': {
      id: '/projects/$projectId/advanced/commands'
      path: '/projects/$projectId/advanced/commands'
      fullPath: '/projects/$projectId/advanced/commands'
      preLoaderRoute: typeof ProjectsProjectIdAdvancedCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsProjectIdHostsRouteChildren {
  ProjectsProjectIdHostsAgentsRoute: typeof ProjectsProjectIdHostsAgentsRoute
  ProjectsProjectIdHostsAuditRoute: typeof ProjectsProjectIdHostsAuditRoute
  ProjectsProjectIdHostsBootstrapRoute: typeof ProjectsProjectIdHostsBootstrapRoute
  ProjectsProjectIdHostsDeployRoute: typeof ProjectsProjectIdHostsDeployRoute
  ProjectsProjectIdHostsLogsRoute: typeof ProjectsProjectIdHostsLogsRoute
  ProjectsProjectIdHostsOverviewRoute: typeof ProjectsProjectIdHostsOverviewRoute
  ProjectsProjectIdHostsRestartRoute: typeof ProjectsProjectIdHostsRestartRoute
  ProjectsProjectIdHostsSecretsRoute: typeof ProjectsProjectIdHostsSecretsRoute
  ProjectsProjectIdHostsSettingsRoute: typeof ProjectsProjectIdHostsSettingsRoute
  ProjectsProjectIdHostsIndexRoute: typeof ProjectsProjectIdHostsIndexRoute
}

const ProjectsProjectIdHostsRouteChildren: ProjectsProjectIdHostsRouteChildren =
  {
    ProjectsProjectIdHostsAgentsRoute: ProjectsProjectIdHostsAgentsRoute,
    ProjectsProjectIdHostsAuditRoute: ProjectsProjectIdHostsAuditRoute,
    ProjectsProjectIdHostsBootstrapRoute: ProjectsProjectIdHostsBootstrapRoute,
    ProjectsProjectIdHostsDeployRoute: ProjectsProjectIdHostsDeployRoute,
    ProjectsProjectIdHostsLogsRoute: ProjectsProjectIdHostsLogsRoute,
    ProjectsProjectIdHostsOverviewRoute: ProjectsProjectIdHostsOverviewRoute,
    ProjectsProjectIdHostsRestartRoute: ProjectsProjectIdHostsRestartRoute,
    ProjectsProjectIdHostsSecretsRoute: ProjectsProjectIdHostsSecretsRoute,
    ProjectsProjectIdHostsSettingsRoute: ProjectsProjectIdHostsSettingsRoute,
    ProjectsProjectIdHostsIndexRoute: ProjectsProjectIdHostsIndexRoute,
  }

const ProjectsProjectIdHostsRouteWithChildren =
  ProjectsProjectIdHostsRoute._addFileChildren(
    ProjectsProjectIdHostsRouteChildren,
  )

interface ProjectsProjectIdRunsRouteChildren {
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
}

const ProjectsProjectIdRunsRouteChildren: ProjectsProjectIdRunsRouteChildren = {
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
}

const ProjectsProjectIdRunsRouteWithChildren =
  ProjectsProjectIdRunsRoute._addFileChildren(
    ProjectsProjectIdRunsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  ProjectsImportRoute: ProjectsImportRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProjectsProjectIdDashboardRoute: ProjectsProjectIdDashboardRoute,
  ProjectsProjectIdHostsRoute: ProjectsProjectIdHostsRouteWithChildren,
  ProjectsProjectIdRunsRoute: ProjectsProjectIdRunsRouteWithChildren,
  ProjectsProjectIdSecretsRoute: ProjectsProjectIdSecretsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdAdvancedCommandsRoute:
    ProjectsProjectIdAdvancedCommandsRoute,
  ProjectsProjectIdAdvancedEditorRoute: ProjectsProjectIdAdvancedEditorRoute,
  ProjectsProjectIdSetupDoctorRoute: ProjectsProjectIdSetupDoctorRoute,
  ProjectsProjectIdSetupFleetRoute: ProjectsProjectIdSetupFleetRoute,
  ProjectsProjectIdSetupSettingsRoute: ProjectsProjectIdSetupSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
