export const WEB_DEPLOY_CREDS_EDITABLE_KEYS = [
  "HCLOUD_TOKEN",
  "GITHUB_TOKEN",
  "SOPS_AGE_KEY_FILE",
] as const

export const WEB_SETUP_REQUIRED_KEYS = [
  "HCLOUD_TOKEN",
  "GITHUB_TOKEN",
  "SOPS_AGE_KEY_FILE",
] as const

export const WEB_DEPLOY_CREDS_VISIBLE_KEYS = [
  "HCLOUD_TOKEN",
  "GITHUB_TOKEN",
  "SOPS_AGE_KEY_FILE",
  "NIX_BIN",
] as const

export const WEB_DEPLOY_CREDS_EDITABLE_KEY_SET = new Set<string>(WEB_DEPLOY_CREDS_EDITABLE_KEYS)
export const WEB_DEPLOY_CREDS_VISIBLE_KEY_SET = new Set<string>(WEB_DEPLOY_CREDS_VISIBLE_KEYS)
