export const setupFieldHelp = {
  hosts: {
    defaultHost: "Default host used by doctor/bootstrap/updates when you leave host unset.",
    editHost: "Select which host config you’re editing under `hosts.<host>`.",
    addHost: "Adds a new host entry under `hosts.<host>` (config only; no infra created yet).",
    enabled: "Toggles whether this host is managed by clawlets.",
    diskDevice: "Block device to install NixOS onto (usually `/dev/sda` on Hetzner). Must start with `/dev/`.",
    targetHost: "SSH destination used for deploy/ops + live schema. Optional until you run server ops; set in Hosts → Settings → Target host (ssh alias or `user@host`).",
    provider: "Infrastructure provider for Day 0 lifecycle. Dashboard host settings currently support `hetzner`.",
    adminCidr: "Which IP addresses can connect to admin SSH during setup (usually your current IP with `/32`). Use Detect to autofill.",
    sshPubkeyFile:
      "Local path to your SSH public key file used during provisioning (for example `~/.ssh/id_ed25519.pub`) for CLI flows. Dashboard deploy requires `fleet.sshAuthorizedKeys`. Generate one if missing: `ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519`.",
    sshExposure: "How SSH is exposed: `bootstrap` (temporary), `tailnet` (recommended), or `public` (least safe).",
    tailnet: "Tailnet integration mode. `tailscale` enables Tailscale-based access; `none` disables it.",
    hetznerServerType: "Hetzner server type (e.g. `cpx32`). Used by provisioning.",
    hetznerLocation: "Hetzner DC location (e.g. `fsn1`).",
    hetznerImage: "Optional Hetzner image override (usually leave empty when using nixos-anywhere).",
    hetznerAllowTailscaleUdpIngress: "Controls inbound UDP/41641 for direct Tailscale WireGuard paths. Disable for relay-only mode and reduced public exposure.",
    hetznerVolumeEnabled: "Attach a dedicated Hetzner volume for durable OpenClaw state and mount it at `/srv/openclaw`.",
    hetznerVolumeSizeGb: "Volume size in GB. Set 0 to disable the volume.",
    flakeHost: "Override the Nix flake host target (advanced; usually leave empty).",
    agentModelPrimary: "Default model identifier used by agents on this host (provider/model).",
    cacheSubstituters: "Nix substituters (binary caches) for this host. One per line. Used by the updater allowlist; manifests may only specify a subset.",
    cacheTrustedPublicKeys: "Nix trusted public keys for this host. One per line. Used by the updater allowlist; manifests may only specify a subset.",
    cacheNetrcEnable: "Enable authenticated cache access via netrc-file (private Garnix/Attic/Harmonia/etc). Secret contents stay in sops; only the secret name is configured here.",
    cacheNetrcSecretName: "Sops secret name containing the netrc file contents (written to cache.netrc.path on the host).",
    cacheNetrcPath: "Filesystem path for netrc-file on the host (default: /etc/nix/netrc).",
    cacheNarinfoCachePositiveTtl: "narinfo-cache-positive-ttl (seconds). Private caches with presigned narinfo URLs (e.g. private Garnix) require this to avoid stale positive cache entries.",
    sshKeyPaste:
      "Paste one or more public keys to append to `fleet.sshAuthorizedKeys` (shared across all hosts). Generate a key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent",
    sshKeyFile: "Read a local `.pub` file and append it to `fleet.sshAuthorizedKeys`.",
    knownHostsFile: "Optionally import entries from your local `known_hosts` into `fleet.sshKnownHosts`.",
  },
  fleet: {
    codexEnable: "Enables Codex integration in the fleet config.",
    resticEnable: "Enables restic backups configuration in the fleet config.",
    resticRepo: "Restic repository URL/path used for backups (only when restic is enabled).",
    jsonEditor: "Edit the full `fleet/clawlets.json` as JSON (validated + atomic write).",
    dotPath: "Dot-path into config (e.g. `fleet.codex.enable`, `hosts.my-host.targetHost`).",
    dotValue: "Value to set as a string (use JSON value if you need objects/arrays/bools/numbers).",
    dotValueJson: "Value to set as JSON (e.g. `true`, `123`, `{...}`, `[...]`).",
  },
  bots: {
    botId: "Stable bot identifier (used in ports/services and config keys). Must match existing fleet conventions.",
  },
  secrets: {
    host: "Host whose encrypted secrets you’re initializing/verifying/syncing.",
    allowPlaceholders: "Allow placeholder secret values during init (unsafe; only for dry scaffolding).",
    adminPassword: "Server admin password (optional). If set, a secure hash is generated automatically.",
    adminPasswordHash: "Precomputed server admin password hash (`$y$…`). Stored as `admin_password_hash`.",
    tailscaleAuthKey: "Tailscale auth key used to join your tailnet (only required when tailnet mode is tailscale).",
    extraSecret: "Additional secret value written to encrypted YAML under `secrets/hosts/<host>`.",
  },
  doctor: {
    host: "Host to run checks against (defaults to config default host).",
    scope: "Subset of checks to run (repo/bootstrap/updates/all).",
  },
  bootstrap: {
    host: "Host entry to bootstrap/provision.",
    mode: "`nixos-anywhere` provisions a fresh server; `image` uses an existing image flow.",
    source: "Pins which git revision nixos-anywhere installs. Workstation uses local HEAD; GitHub uses the last pushed origin default.",
    lockdownAfter: "After bootstrap, waits for the host to join the tailnet and then runs lockdown (removes public SSH in Hetzner firewall). Recommended when using Tailscale.",
    force: "Skip doctor gate checks. Risky; prefer fixing doctor findings first.",
    dryRun: "Show commands without executing (safe preview).",
  },
} as const
